const fs = require('fs');
const path = require('path');
const { spawn, execSync } = require('child_process');

const originalSchemaPath = path.join(__dirname, 'prisma', 'schema.prisma');
const sqliteSchemaPath = path.join(__dirname, 'prisma', 'schema.sqlite.prisma');

const originalContent = fs.readFileSync(originalSchemaPath, 'utf-8');

// Switch schema to SQLite
let sqliteSchema = originalContent
  // Only replace the provider inside the datasource block, not the generator block
  .replace(/datasource\s+db\s*{[^}]*provider\s*=\s*"[^"]+"/, (match) => {
    return match.replace(/provider\s*=\s*"[^"]+"/, 'provider = "sqlite"');
  })
  .replace(/\s*directUrl\s*=\s*env\(["']DIRECT_URL["']\)\s*\n?/, '\n');

// Add a warning header so developers don't accidentally edit it
const header = `// ====================================================================
// AUTO-GENERATED FILE for local SQLite development.
// DO NOT EDIT THIS FILE DIRECTLY!
// Edit schema.prisma instead, and run \`npm run dev:local\` to regenerate.
// ====================================================================\n\n`;

fs.writeFileSync(sqliteSchemaPath, header + sqliteSchema);
console.log('✅ Generated schema.sqlite.prisma for local development');

// Set DATABASE_URL for SQLite
process.env.DATABASE_URL = 'file:./dev.db';

// Generate Prisma client for SQLite using the generated schema
try {
  console.log('⏳ Generating Prisma client for SQLite...');
  execSync('npx prisma generate --schema=prisma/schema.sqlite.prisma', { stdio: 'inherit', env: { ...process.env, DATABASE_URL: 'file:./dev.db' } });
  console.log('✅ Prisma client generated');
} catch (e) {
  console.error('❌ Failed to generate Prisma client');
  process.exit(1);
}

// Ensure SQLite DB exists
try {
  execSync('npx prisma db push --accept-data-loss --schema=prisma/schema.sqlite.prisma', { stdio: 'inherit', env: { ...process.env, DATABASE_URL: 'file:./dev.db' } });
  console.log('✅ SQLite database ready');
} catch (e) {
  console.error('⚠️  Warning: db push had issues, but continuing...');
}

// Start Next.js dev server
console.log('\n🚀 Starting local dev server (SQLite)...\n');
const child = spawn('npx', ['next', 'dev', '-H', '0.0.0.0'], {
  stdio: 'inherit',
  shell: true,
  env: { ...process.env, DATABASE_URL: 'file:./dev.db' },
});

child.on('close', (code) => {
  process.exit(code || 0);
});
